### ISSUE TITLE
switchx sampler won't build on main

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#1788]
The usual mad, opensm, rdma packages are installed; the ibnet sampler compiles.

error example:
```
  CC       libswitchx_la-switchx.lo
../../../../ldms/src/sampler/switchx.c:71:10: fatal error: iba/ib_types.h: No such file or directory
 #include <iba/ib_types.h>
```

**Comment by morrone** [comment]
Hah! It looks like in opensm the header moved to <infiniband/iba/ib_types.h>. But that ip_types.h header has the same issue we have. They do ```#include <complib/cl_types.h>```, but they need to switch to ```#include <infiniband/complib/cl_types.h>```.

But even if we update our include, and upstream fixes their include, the next problem we would hit is this include in the sampler:

```
#include "ibdiag_common.h"
```

We don't have a file by that name, and didn't in b4.4 either. Maybe it is supposed to come from an external source? But I don't see that externally either.

But I do have a commit in PR #1805 that updates the ib_types.h include path.

**Comment by morrone** [comment]
I don't suspect that the switchx sampler would compile on b4.4 either, so we can maybe remove the v4.5.1 milestone. It does not appear to be a regression new to main, at least.

**Comment by morrone** [comment]
If PR #1918 lands it will remove the switchx plugin and make this issue moot.
