### ISSUE TITLE
b4.5 top broken

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ldms#2374]
as of https://github.com/ovis-hpc/ldms/commit/95a745deee22a1608130dfbaa202b88ad960841b ldms b4.5 tip doesn't build on TOSS4/rehl8.10 (cython 0.28.1, python3.6.8). It gets the following error:

```
make[4]: Entering directory '/home/baallan/ovis/repos/b45.ovis/obj/ldms/python'
  CC       ldms_la-ldms_pyx.lo
ldms_pyx.c: In function 'PyInit_ldms':
ldms_pyx.c:112439:17: error: 'CYTHON_HEX_VERSION' undeclared (first use in this function); did you mean 'PYTHON_ABI_VERSION'?
   __pyx_t_7 = ((CYTHON_HEX_VERSION >= 0x03010000) != 0);
                 ^~~~~~~~~~~~~~~~~~
                 PYTHON_ABI_VERSION
ldms_pyx.c:112439:17: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by narategithub** [comment]
From our README: Cython >= 0.29
